<?php

namespace Plugin\FlashSale\Repository;

use Eccube\Repository\AbstractRepository;
use Plugin\FlashSale\Entity\Config;
use Plugin\FlashSale\Entity\Event;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends AbstractRepository
{
    /**
     * EventRepository constructor.
     *
     * @param RegistryInterface $registry
     */
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, Event::class);
    }

    /**
     * @param int $id
     *
     * @return null|Config
     */
    public function get($id = 1)
    {
        return $this->find($id);
    }
}
