<?php

namespace Plugin\FlashSale\Repository;

use Eccube\Repository\AbstractRepository;
use Plugin\FlashSale\Entity\Config;
use Plugin\FlashSale\Entity\FlashSale;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * FlashSaleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FlashSaleRepository extends AbstractRepository
{
    /**
     * FlashSaleRepository constructor.
     *
     * @param RegistryInterface $registry
     */
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, FlashSale::class);
    }

    /**
     * @param int $id
     *
     * @return null|Config
     */
    public function get($id = 1)
    {
        return $this->find($id);
    }

    /**
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function getQueryBuilderAll()
    {
        $qb = $this->createQueryBuilder('fl');
        $qb->orderBy('fl.from_time', 'DESC')
            ->addOrderBy('fl.id', 'DESC');

        return $qb;
    }
}
