<?php
namespace Plugin\FlashSale\Service\PurchaseFlow\Processor;

class FSDeliveryFeePreprocessor extends \Eccube\Service\PurchaseFlow\Processor\DeliveryFeePreprocessor
{

    public function process(\Eccube\Entity\ItemHolderInterface $itemHolder, \Eccube\Service\PurchaseFlow\PurchaseContext $context)
    {
        die(__METHOD__);
        parent::process($itemHolder, $context); // TODO: Change the autogenerated stub
    }
}
