services:
    Plugin\FlashSale\Service\PurchaseFlow\Processor\FSShoppingProcessor:
        lazy: true
        public: true
        autowire: true
        tags:
          - {name: eccube.discount.processor}
    Plugin\FlashSale\Service\PurchaseFlow\Processor\FSOrderItemProcessor:
        lazy: true
        public: true
        autowire: true
        tags:
          - {name: eccube.purchase.processor}

    Plugin\FlashSale\Service\FlashSaleService:
        public: true
        autowire: true

    Plugin\FlashSale\Service\Promotion\PromotionFactory:
        public: true
        autowire: true
        lazy: true

    Plugin\FlashSale\Service\Condition\ConditionFactory:
        public: true
        autowire: true
        lazy: true

    Plugin\FlashSale\Service\Rule\RuleFactory:
        public: true
        autowire: true
        lazy: true